services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./project:/project/
#    environment:
#      - DJANGO_SETTINGS_MODULE:project.settings
#    links:
#      - db
#    depends_on:
#      - db

    